### ISSUE TITLE
Can't perform initial setup

### ISSUE THREAD

**Issue by gokuu** [jlesage/docker-crashplan-pro#144]
Hello,

I'm trying use your image to have Crashplan to backup my home server, but I can't even perform the initial setup.

I login to my account, and I'm presented with the screen "Looks like this device was never backed up".
Whether I press "Add new device" or "Replace existing", the screen changes to the next 'page', but immediately moves back to the previous one.

I'm deploying using docker-compose, and using traefik as a reverse proxy. I've tried either via web or VNC, but both have the same problem. 
Here's my docker-compose relevant configuration:
```yaml
  crashplan:
    image: jlesage/crashplan-pro
    volumes:
      - ~/docker/config/crashplan:/config
      - /:/storage:ro
    ports:
      - 5900:5900
    labels:
      traefik.backend: crashplan
      traefik.backend.loadbalancer.swarm: 'true'
      traefik.enable: 'true'
      traefik.frontend.rule: Host:crashplan.domain.tld
      traefik.port: 5800
```

Can anyone shed any light on how to fix this?
Thanks
