### ISSUE TITLE
Unable to connect to destination

### ISSUE THREAD

**Issue by djbacon** [jlesage/docker-crashplan-pro#300]
Hello!

I'm running docker version on Synology NAS and for a few days now I'm seeing error "Unable to connect to destination fox 9 days".  
I recently upgraded docker-crashplan-pro so I guess something went wrong. Also Code24 forced me to add Two Way Authentication, so maybe that has something to do with this. 
Please advise how to fix it.

**Comment by grissoma** [comment]
I also am experiencing this on all my backup sets... odd part is the times are different. I have 4 backup sets, and each one is "Unable to connect to destination for [5.7, 9.7, 8.8, 8.7] days."
I'm running on a QNAP TS-453D, using Container Station.
My config is:
```
version: '3'

services:
  crashplan-pro:
    image: jlesage/crashplan-pro
    hostname: crashplan
    container_name: crashplan
    environment:
      - USER_ID=1002
      - GROUP_ID=100
      - DISPLAY_HEIGHT=900
      - DISPLAY_WIDTH=1440
      - TZ=America/Chicago
      - KEEP_APP_RUNNING=1
      - CRASHPLAN_SRV_MAX_MEM=4096M
    volumes:
      - /share/CACHEDEV1_DATA/Docker/Code42:/config
      - /share/CACHEDEV1_DATA:/storage:ro
    ports:
      - 5900:5900
    restart: unless-stopped
```
Thanks!!
