### ISSUE TITLE
Crashplan crashes with trying to select "Other" location during restore setup

### ISSUE THREAD

**Issue by johnmckinzie** [jlesage/docker-crashplan-pro#342]
I'm running this image on an Asustor AS6602T using the Portainer and the following Compose file (999 is admin user/group on NAS):

```
version: '3'
services:
  crashplan-pro:
    hostname: **************
    container_name: crashplan-pro
    image: jlesage/crashplan-pro
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - KEEP_APP_RUNNING=1
      - CRASHPLAN_SRV_MAX_MEM=3G
      - USER_ID=999
      - GROUP_ID=999
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "/home/admin/crashplan/config:/config"
      - "/volume2/storage:/storage"
```

When I try and setup a restore and get to the **Restore File Options** pop-up, Crashplan crashes when I select **Other** from the **Save selected files to** dropdown list. Below of a video of the issue:

https://www.youtube.com/watch?v=7dNozloJSdI
