### ISSUE TITLE
Stuck at "Preparing to run backup"

### ISSUE THREAD

**Issue by theimplord** [jlesage/docker-crashplan-pro#354]
Just started using this docker container for an account that had been windows for years. After moving HD data over, and spending a week, it's finally synchronized and appears ready to backup. It doesn't do anything at all. I can click "Run backup now" for a given backup set, but it just says stuck on "Preparing to run backup" (Restore also isn't working, but let's get upload first so CP doesn't delete my files on their server).

History doesn't have anything interesting:
```
01/30/22 07:17 PM	Local Drive: R not ready for backup. Reason: The backup location is not accessible
01/30/22 07:26 PM	[Marvel Comics (L)] Backup to CrashPlan Central will take priority until complete (up to 24 hours)
```

The container's logs don't say anything. The application just sits like this.

![image](https://user-images.githubusercontent.com/96933732/151715002-6c08052a-eb4e-4dfa-aaf2-52f07edc5c85.png)

**Comment by jlesage** [comment]
Can you share the `docker run` command you used to create the container ?

**Comment by theimplord** [comment]
I'm using Docker compose via Portainer.

```
version: '3'
services:
  crashplan-pro:
    image: jlesage/crashplan-pro
    ports:
      - "5800:5800"
    environment:
      - CRASHPLAN_SRV_MAX_MEM=3072M
      - KEEP_APP_RUNNING=1
      - USER_ID=998
      - GROUP_ID=100
    volumes:
      - "/srv/dev-disk-by-uuid-b53a817a-d6e2-4e1c-892b-a5d5952cc613/voltron/crashplan:/config:rw"
      - "/srv/dev-disk-by-uuid-09e55364-b94a-4104-965a-655747f2f365/Photos:/storage/photos:ro"
      - "/srv/0260abda-c687-4bc8-af04-0c4297260d82/Backups:/storage/backups:ro"
      - "/srv/0260abda-c687-4bc8-af04-0c4297260d82/Documents:/storage/documents:ro"
    restart: unless-stopped
```
