### ISSUE TITLE
CRASHPLAN_SRV_MAX_MEM doesn't appear to be working

### ISSUE THREAD

**Issue by bmorgenthaler** [jlesage/docker-crashplan-pro#392]
Running the latest version and trying to set CRASHPLAN_SRV_MAX_MEM to 8GB
```
services:
  crashplan-pro:
    image: jlesage/crashplan-pro
    hostname: crashplan
    restart: unless-stopped
    environment:
      - TZ = "US/Central"
      - USER_ID = 1002
      - KEEP_APP_RUNNING = 1
      - CRASHPLAN_SRV_MAX_MEM = 8192M
    ports:
      - "5800:5800"
    volumes:
      - "config:/config"
      - "data:/storage"
```
Looking at the logs in config/logs this is what I see 
```
# grep Xmx *
app.log:JavaOptions  = [-Dsun.jnu.encoding=UTF-8, -Dfile.encoding=UTF-8, -Dsun.net.inetaddr.ttl=300, -Dnetworkaddress.cache.ttl=300, -Dsun.net.inetaddr.negative.ttl=0, -Dnetworkaddress.cache.negative.ttl=0, -Dapp=Code42Service, -DappBaseName=Code42, -Djna.nosys=true, -Djava.awt.headless=true, -DCode42=Code42, -Dnashorn.args=--no-deprecation-warning, -Dc42.installation.enforcement.enabled=true, -XX:-ShrinkHeapInSteps, -XX:MaxHeapFreeRatio=30, -XX:MinHeapFreeRatio=15, -Djava.library.path=/usr/local/crashplan/nlib, -Djna.library.path=/usr/local/crashplan/nlib, -Dc42.log.config=/usr/local/crashplan/conf/service.log.xml, -Xmx1024M]
app.log:JVM_ARGS     = [-Xmx1024M]
engine_output.log:-Xmx1024M
service.log.0:[11.04.22 01:13:47.901 INFO  main           com.backup42.service.CPService] JavaOptions = [-Dsun.jnu.encoding=UTF-8, -Dfile.encoding=UTF-8, -Dsun.net.inetaddr.ttl=300, -Dnetworkaddress.cache.ttl=300, -Dsun.net.inetaddr.negative.ttl=0, -Dnetworkaddress.cache.negative.ttl=0, -Dapp=Code42Service, -DappBaseName=Code42, -Djna.nosys=true, -Djava.awt.headless=true, -DCode42=Code42, -Dnashorn.args=--no-deprecation-warning, -Dc42.installation.enforcement.enabled=true, -XX:-ShrinkHeapInSteps, -XX:MaxHeapFreeRatio=30, -XX:MinHeapFreeRatio=15, -Djava.library.path=/usr/local/crashplan/nlib, -Djna.library.path=/usr/local/crashplan/nlib, -Dc42.log.config=/usr/local/crashplan/conf/service.log.xml, -Xmx1024M]
service.log.0:[11.04.22 01:13:47.902 INFO  main           com.backup42.service.CPService] JVM_ARGS = [-Xmx1024M]
```
I've tried to stop the container, remove CRASHPLAN_SRV_MAX_MEM and set the memory in jvm_args with `-Xmx8192M` but it still reverts back to 1024M.

Unfortunately I'm backing up over 4TB of files and Crashplan keeps crashing.

**Comment by uberwrensch** [comment]
@bmorgenthaler if that is from your `docker-compose` file, then I don't think there's supposed to be spaces around `=` var assignment. Are the other envvars working?

Try this?
`CRASHPLAN_SRV_MAX_MEM=8192M`

**Comment by dghodgson** [comment]
You're using array syntax which requires no spaces around the equals sign 
https://docs.docker.com/compose/compose-file/#environment

FWIW map syntax works fine for me:
```
version: '3'
services:
  crashplan-pro:
    image: jlesage/crashplan-pro
    container_name: crashplan-pro
    restart: always
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 3G
    environment:
      USER_ID: 0
      GROUP_ID: 0
      TZ: America/Los_Angeles
      CRASHPLAN_SRV_MAX_MEM: 9G
 ```
