### ISSUE TITLE
UID and GID don't seem to work

### ISSUE THREAD

**Issue by LorneCash** [jlesage/docker-crashplan-pro#422]
I'm running this container on a Synology and I'm having trouble viewing folder contents.
I've set the parameters USER_ID and GROUP_ID but I'm still unable to view folder contents.  The only way I've been able to view the contents is if I add EVERYONE:ro permission to each folder I want to backup.  This is really not an acceptable solution long term and if anyone can help please lmk.  I'm really not sure if this is a bug with the container or if I'm missing something.

Using Portainer I've connected to the Exec Console using /bin/sh:

As root I can cd and ls to see all the files and I get this:

> /tmp # getent passwd
> root::0:0::/root:/sbin/nologin
> app::1000:1000::/config:/sbin/nologin

As XXXX I CANNOT cd and ls to see all the files and I get this:

> /tmp $ getent passwd
> root::0:0::/root:/sbin/nologin
> app::XXXX:XXX::/config:/sbin/nologin

I'm not sure if that means anything (I'm not that familiar with Linux, I just searched how to list all users).

> /storage $ ls Logs
> ls: can't open 'Logs': Permission denied

For reference here's my Portainer Stack (Docker-Compose file):

```
version: '3'
services:
  crashplan-pro:
    container_name: CrashPlan
    hostname: XXXXXX
    image: jlesage/crashplan-pro
    ports:
      - "5800:5800"
    volumes:
      - "/volume1/docker/crashplan:/config:rw"
      - "/volume1:/storage:ro"
    environment:
    - GROUP_ID=XXX
    - USER_ID=XXXX
    - CRASHPLAN_SRV_MAX_MEM=2048M
    restart: unless-stopped
```
