### ISSUE TITLE
Fresh container created with an existing config directory requires taking ownership of backup.

### ISSUE THREAD

**Issue by stuckj** [jlesage/docker-crashplan-pro#43]
I had originally used the non-pro container for several months. I switched to the pro account and used the same config volume with the pro container. Upon first start it required login to crashplan and required taking ownership of an existing backup (i.e., acted like there was no existing configuration). I exec'd a terminal to the docker container and verified the config files did exist just to be sure I hadn't messed the mount up. They did. So, I figured this was a one time thing so took ownership of the files. All was well. The next day I made a change to my docker-compose so deleted / re-created the container. And, once again had to login and take ownership of a backup.

It seems like the configuration volume either isn't being used or doesn't contain the full information required to prevent needing to keep from taking ownership of a backup again upon re-creating the docker container.

Have you seen this issue?

I don't believe I saw this with the old crashplan image. This seems unique to the pro image (at least since I've updated to it in the past week).

**Comment by jlesage** [comment]
This definitely should not occur.  Can you provide your compose file? Also, what is the content of your config directory on the host?

**Comment by johnnysocko** [comment]
Any followup on this?  stuckj is that still an issue.  Would like to know before I recreate a working container.  Thanks

**Comment by stuckj** [comment]
This is definitely still an issue for me. I just mistakenly upgraded the container again today and it unfortunately now shows crashplan in what looks like an initial configuration state (no files selected, nothing backed up, etc). I'll put my compose file at the end of this comment. But, lemme give you some context first. What got me into this today was I pruned unused images in my docker host today as I had run out of space. I had containers stopped at the time so this effectively deleted the container for crashplan. Which shouldn't be an issue since I can just re-create it. This is where it basically acted like an upgrade for me today (brand new container).

The config directory is mapped to an NFS volume I have on a freenas server (that NFS mount is handled on the docker host...the container just does a normal mapping to a dir on the host filesystem).

Since it's ZFS and I have daily snapshots I can see the configuration from yesterday (when it was working). Of particular interest is the `conf/my.service.xml` file. In my snapshot it's a 26789 byte file with my file selection in it. In the current version in my config directory in freenas it's 10548 bytes and looks like a freshly initialized version of the file. So, I tried stopping the container, restoring that directory from snapshot, and restarting it. As soon as the container finished starting that file was re-initialized to a 10548 byte file and crashplan again showed as being reset.

So, it looks like if the container is destroyed and re-created it's wiping out some or all of the configuration in the mounted config directory as part of the initialization process of the new container. That's my theory at least...no idea if that's what's actually happening, but that's effectively what I'm seeing.

I'm using rancher as my orchestration manager. I don't directly map in /storage, but I map in files below it (so /storage itself gets plopped in an anonymous volume). Here's the compose I'm using:

```
version: '2'
services:
  crashplan:
    image: jlesage/crashplan-pro:latest
    environment:
      CRASHPLAN_SRV_MAX_MEM: 6G
      VNC_PASSWORD: <REDACTED>
    stdin_open: true
    volumes:
    - /mnt/root-dataset/docker-storage/crashplan-config-data:/config
    - /mnt/root-dataset:/storage/nas/mnt/root-dataset:ro
    - /mnt/fast-dataset:/storage/nas/mnt/fast-dataset:ro
    - /mnt/backup-root-dataset:/storage/nas/mnt/backup-root-dataset:ro
    - /mnt/iso-dataset:/storage/nas/mnt/iso-dataset:ro
    dns:
    - <REDACTED>
    tty: true
    expose:
    - '5800'
    labels:
      rap.le_email: <REDACTED>
      rap.port: '5800'
      rap.le_test: 'false'
      io.rancher.container.network: 'true'
      io.rancher.scheduler.affinity:host_label: prod=true,dns-exposed=true
      rap.le_host: <REDACTED>
      rap.https_listen_ports: '5800'
      io.rancher.container.pull_image: always
      rap.host: <REDACTED>
      rap.proto: http
```

For now I'm going to restore my entire docker host VM from yesterday's snapshot (I've got my VMs snapshotted too thankfully) which should get me running again hopefully. But, I'd be happy to debug this further for you if it's helpful. I feel a little unsafe as it currently is as it's too easy to mess it up and restoring from snapshots is a pain. I'd be happy to send any logs or info that might help with looking into it.
